{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
rules:
  {{/* Required for Drain/Taint Node Attacks */}}
  - apiGroups: [""]
    resources:
      - pods/eviction
    verbs:
      - create
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - patch
{{- template "defaultPermissions" . }}
{{- end }}
